config/routes.rb
Myapp::Application.routes.draw do

  root 'gestion#index'

  get 'login' => 'gestion#login', as: 'login'
  post 'login' => 'gestion#login'
  get 'logout' => 'gestion#logout', as: 'logout'


  namespace :gestion do
    resources :ventas do
      post 'aniade_venta/:servicio' => 'ventas#aniade_venta'
      post 'aniade_producto/:producto' => 'ventas#aniade_producto'
      post 'elimina_linea_venta/:id/:tipo' => 'ventas#elimina_linea_venta'
      post 'cierra_venta' => 'ventas#cierra_venta'
    end
    resources :servicios
    resources :productos
    resources :informes do
      collection do
        get 'generar_pdf/' => 'informes#generar_pdf', as: 'generar_pdf'
      end
    end
    resources :estadisticas do
      collection do
        get 'devuelve_productos/:current_week' => 'estadisticas#devuelve_servicios', as: 'devuelve_servicios'
      end
    end
    resources :pagos
    resources :clientes do
      collection do
        get 'filtrar_clientes/:cliente' => 'clientes#filtrar_clientes', as: 'filtrar_clientes'
        get 'resetear_filtros/' => 'clientes#resetear_filtros', as: 'resetear_filtros'
      end
      member do
        get 'new_tinte'
        get 'edit_tinte/:tinte_id' => 'clientes#edit_tinte', as: 'editar_tinte'
      end
    end
    resources :tintes
    resources :clientes_tintes
    resources :configuraciones
    resources :citas
    resources :gasolinas

    resources :roles
    resources :empresas
    resources :usuarios
    resources :permisos
  end
end

app/controllers/gestion/administraciones_controller.rb
class Gestion::AdministracionesController < GestionController

  skip_before_action :verify_authenticity_token

  def index
  end

  def create
    cita = Cita.create(permit_params)
    redirect_to gestion_citas_path
  end

  def permit_params
    params.require(:cita).permit(:cliente_id, :fecha_inicio)
  end

  private

  def obtener_clientes
    @clientes = Cliente.where('activo = true').order('id').map {|c| [c.nombre_completo, c.id]}
  end

  def obtener_citas
    @citas = []
    citas = Cita.all.order('id')
    citas.each do |c|
      @citas << {:id => c.id, :title => "Cita reservada con #{Cliente.find(c.cliente_id).nombre_completo}", :start => c.fecha_inicio}
    end
    @citas = @citas.to_json
  end

end

app/controllers/gestion/citas_controller.rb
class Gestion::CitasController < GestionController

  skip_before_action :verify_authenticity_token

  def index
    obtener_clientes
    obtener_citas
    @cita = Cita.new
    @cliente = Cliente.new
    @horas = [['30 minutos', 30],['1 hora',60],['1 hora y media', 90], ['2 horas', 120]]
  end

  def create
    if params[:cita][:cliente_id].blank? #Si me viene vacío quiere decir que creo un nuevo cliente
      params[:cliente][:nombre_completo_dn] = "#{params[:cliente][:nombre]} #{params[:cliente][:apellidos]}"
      params[:cliente][:activo] = true
      cliente = Cliente.create(permit_params_cliente)
      params[:cita][:cliente_id] = cliente.id
    end
    a = 0
    fecha_inicio = Date.strptime(params[:cita][:fecha_inicio], '%Y-%m-%d %H:%M')
    hora_inicio = DateTime.strptime(params[:cita][:fecha_inicio], '%Y-%m-%d %H:%M').to_s(:time)
    hora_fin = (DateTime.strptime("#{fecha_inicio} #{hora_inicio}", '%Y-%m-%d %H:%M').to_time + (params[:cita][:fecha_fin].to_i.minutes)) - 2.hour
    fecha_fin = DateTime.strptime("#{hora_fin}", '%Y-%m-%d %H:%M:%S')
    params[:cita][:fecha_fin] = fecha_fin
    cita = Cita.create(permit_params)
    redirect_to gestion_citas_path
  end

  def permit_params
    params.require(:cita).permit(:cliente_id, :fecha_inicio, :fecha_fin)
  end

  def permit_params_cliente
    params.require(:cliente).permit(:nombre, :apellidos, :sexo, :telefono, :activo, :nombre_completo_dn)
  end


  private

  def obtener_clientes
    @clientes = Cliente.where('activo = true').order('id').map {|c| [c.nombre_completo, c.id]}
  end

  def obtener_citas
    @citas = []
    citas = Cita.all.order('id')
    citas.each do |c|
      @citas << {:id => c.id, :title => "Cita reservada con #{Cliente.find(c.cliente_id).nombre_completo}", :start => c.fecha_inicio, :end => c.fecha_fin, color:"##{(Cliente.find(c.cliente_id).sexo == "Hombre") ? "4682B4" : "DB7093" }"}
    end
    @citas = @citas.to_json
  end

end

app/controllers/gestion/clientes_controller.rb
class Gestion::ClientesController < GestionController

  skip_before_action :verify_authenticity_token

  def index
    @clientes = find_clientes

  end

  def new
    fill_form
    @cliente = Cliente.new
  end

  def create
    if params[:cliente_tinte].present?
      tinte = Tinte.find(params[:cliente_tinte][:tinte_id])
      params[:cliente_tinte][:cliente_id] = params[:cliente_tinte][:cliente_id]
      params[:cliente_tinte][:producto_id] = tinte.id
      tinte_cliente = TinteCliente.create(permit_params_cliente_tinte)
      if tinte_cliente.valid?
        redirect_to edit_gestion_cliente_path(params[:cliente_tinte][:cliente_id])
      else
        @cliente_tinte = tinte_cliente
        render :new
      end
    else
      params[:cliente][:nombre_completo_dn] = "#{params[:cliente][:nombre]} #{params[:cliente][:apellidos]}"
      cliente = Cliente.create(permit_params)

      if cliente.valid?
        redirect_to gestion_clientes_path
      else
        @cliente = cliente
        fill_form
        render :new
      end
    end

  end

  def edit
    fill_form
    @cliente = Cliente.find(params[:id])
    @cliente_tintes = TinteCliente.where('cliente_id = ?', @cliente.id)
    @tintes = Tinte.where('tipo ILIKE ?', '%tinte%').order('activo DESC')
  end

  def update
    cliente = Cliente.find(params[:id])
    params[:cliente][:nombre_completo_dn] = "#{params[:cliente][:nombre]} #{params[:cliente][:apellidos]}"

    if cliente.update_attributes(permit_params)
      redirect_to gestion_clientes_path
    else
      @cliente = cliente
      redirect_to edit_gestion_cliente_path cliente.id
    end
  end

  def new_tinte
    fill_form_tintes
    @cliente = Cliente.find(params[:id])
    @cliente_tinte = TinteCliente.new
  end

  def editar_tinte
    fill_form_tintes
    @cliente = Cliente.find(params[:id])
    @cliente_tinte = TinteCliente.find(params[:tinte_id])
  end

  def fill_form
    @sexo = [['Hombre', 'Hombre'], ['Mujer', 'Mujer']]
  end

  def fill_form_tintes
    @tintes = Tinte.where('tipo ILIKE ?', '%tinte%').order('activo DESC').map { |t| [t.nombre, t.id] }
  end

  def find_clientes
    clientes = Cliente.order('created_at DESC')
    if session[:filter_cliente_nombre].present?
      clientes = clientes.where('nombre_completo_dn ILIKE ?', "%#{session[:filter_cliente_nombre]}%")
    end
    clientes
  end

  def filtrar_clientes
    session[:filter_cliente_nombre] = params[:cliente_nombre] if params[:cliente_nombre].present?
    redirect_to gestion_clientes_path
  end

  def resetear_filtros
    session.delete(:filter_cliente_nombre)
    redirect_to gestion_clientes_path
  end

  def permit_params
    params.require(:cliente).permit(:nombre, :apellidos, :sexo, :telefono, :activo, :nombre_completo_dn)
  end

  def permit_params_cliente_tinte
    params.require(:cliente_tinte).permit(:cliente_id, :tinte_id, :nombre_dn)
  end

end

app/controllers/gestion/configuraciones_controller.rb
class Gestion::ConfiguracionesController < GestionController

end

app/controllers/gestion/empresas_controller.rb
class Gestion::EmpresasController < GestionController

  def index
    @empresas = Empresa.all.order('id DESC')
  end

  def new
    @empresa = Empresa.new
  end

  def create
    empresa = Empresa.create(permit_params)

    if empresa.valid?
      redirect_to gestion_empresas_path
    else
      @empresa = empresa
      render :new
    end
  end

  def edit
    @empresa = Empresa.find(params[:id])
  end

  def update
    empresa = Empresa.find(params[:id])
    if empresa.update_attributes(permit_params)
      redirect_to gestion_empresas_path
    else
      @empresa = empresa
      redirect_to edit_gestion_empresa_path(empresa.id)
    end
  end

  def destroy
    empresa = Empresa.find(params[:id])
    empresa.destroy
    redirect_to gestion_empresas_path
  end


  def permit_params
    params.require(:empresa).permit(:iva, :comision_tarjeta, :stock_bajo, :nombre)
  end
end

app/controllers/gestion/estadisticas_controller.rb
class Gestion::EstadisticasController < GestionController

  def index
    begin
      ventas = Venta.where('cerrada = ?', true) #Sacamos todas las ventas cerradas para mostrar los datos en pantalla según la caja

      #Semana en curso
      ventas_semana_en_curso = ventas.where("created_at >= ?", Time.current.beginning_of_week)

      from = Time.current.beginning_of_week.beginning_of_day
      to = Time.current.end_of_week

      ventas_semana_total_hm = get_ventas_periodo(from, to)
      @ventas_semana_total = ventas_semana_total_hm[1].to_json

      @ventas_semana = ventas_semana_total_hm[0]
      @pagos_tarjeta = ventas_semana_total_hm[2].where("tipo_pago = ?", 'Tarjeta').count
      @pagos_efectivo = ventas_semana_total_hm[2].where("tipo_pago = ?", 'Efectivo').count

      total_comision = 0
      ventas_semana_total_hm[2].where("tipo_pago = ?", 'Tarjeta').each do |c|
        total_comision = total_comision + c.comision_tarjeta
      end

      @total_comision = total_comision

      @iva_repercutido = 0
      ventas_semana_en_curso.each do |vsc|
        @iva_repercutido = @iva_repercutido + vsc.iva
      end if @ventas_semana > 0

      @iva_soportado = 0
      compras_semana_en_curso = Producto.where("fecha_ultima_compra >= ?", Time.current.beginning_of_week)
      compras_semana_en_curso.each do |csc|
        @iva_soportado = @iva_soportado + csc.iva_compra
      end if compras_semana_en_curso.count > 0


      from_semana_anterior = Time.current.beginning_of_week - 7.days
      to_semana_anterior = Time.current.beginning_of_week

      ventas_semana_anterior = get_ventas_periodo(from_semana_anterior, to_semana_anterior)
      @ventas_semana_anterior_total = ventas_semana_anterior[1].to_json


      @diferencia_ventas = devuelve_diferencia(ventas_semana_anterior[0], @ventas_semana)
      @ventas_semana_anterior = ventas_semana_anterior[0]

      @ingresos_semana = ingresos (ventas_semana_en_curso) #Ingresos de la semana en curso
      @ingresos_semana_anterior = ingresos(ventas_semana_anterior[2])


      @diferencia_ingresos = devuelve_diferencia(@ingresos_semana_anterior, @ingresos_semana)


      #Mes en curso
      ventas_mes = ventas.where("created_at >= ? AND created_at <= ?", (Time.current.beginning_of_month), Time.current.end_of_month)
      @ventas_mes = ventas_mes.count
      @ingresos_mes = ingresos(ventas_mes)

      ventas_mes_anterior = ventas.where("created_at >= ? AND created_at <= ?", (Time.current.beginning_of_month - 1.month), Time.current.end_of_month - 1.month)
      num_ventas_mes_anterior = ventas_mes_anterior.count

      @diferencia_ventas_meses = devuelve_diferencia(num_ventas_mes_anterior, @ventas_mes)

      ingresos_mes_anterior = ventas.where("created_at >= ? AND created_at <= ?", (Time.current.beginning_of_month - 1.month), Time.current.end_of_month - 1.month)
      total_ingresos_mes_anterior = ingresos(ingresos_mes_anterior)

      @diferencia_ingresos_meses = devuelve_diferencia(total_ingresos_mes_anterior, @ingresos_mes)


      #General


      @ventas = ventas

      #Sacamos los gastos del mes y después calculamos la diferencia para saber si hay beneficio.
      pagos = Pago.where('ultimo_pago >= ? AND ultimo_pago <= ?', Time.current.beginning_of_month, Time.current.end_of_month)
      @total_gastos = devuelve_total_gastos(pagos)
      @total_mes = ingresos_gastos(@ingresos_mes, @total_gastos)

    rescue => e
      e.backtrace
    end
  end

  def comparacion_ventas
    from = Time.current.beginning_of_week.beginning_of_day
    to = Time.current.end_of_week

    ventas_semana_total_hm = get_ventas_periodo(from, to)
    @ventas_semana_total = ventas_semana_total_hm[1].to_json

    #Ventas de la semana anterior
    from_semana_anterior = Time.current.beginning_of_week - 7.days
    to_semana_anterior = Time.current.beginning_of_week

    ventas_semana_anterior = get_ventas_periodo(from_semana_anterior, to_semana_anterior)
    @ventas_semana_anterior_total = ventas_semana_anterior[1].to_json

    return @ventas_semana_total, @ventas_semana_anterior
  end

  def devuelve_servicios
    begin
      #Sacamos las ventas de esta semana si nos llega true, sino las del mes.
      if params[:current_week] == 'true'
        periodo_inicio = Time.current.beginning_of_week
        periodo_fin = Time.current.end_of_week.strftime("%d/%m/%Y")
      else
        periodo_inicio = Time.current.beginning_of_month.strftime("%d/%m/%Y")
        periodo_fin = Time.current.end_of_month.strftime("%d/%m/%Y")
      end

      #Sacamos los ID's de las ventas para buscar los servicios.
      ventas_ids = Venta.where('cerrada = ? AND created_at >= ? AND created_at <= ?', true, periodo_inicio, periodo_fin).ids #Sacamos los IDS de las ventas de la semana
      servicio_venta = ServicioVenta.where('venta_id IN (?) AND servicio_id IS NOT NULL', ventas_ids).order('servicio_id')
      data = {}
      servicio_id = 0
      usado = 0
      servicio_venta.each do |serven|
        if servicio_id != serven.servicio_id
          usado = 0
          usado = usado + 1
          servicio_id = serven.servicio_id
        else
          usado = usado + 1
        end
        data[serven.servicio_nombre_dn.to_sym] = {usado: usado}
      end if servicio_venta.count > 0
      data.to_json
      render :json => data
    rescue => e
      e.backtrace
    end
  end


  private
  def ingresos (ventas)
    ingresos_totales = 0
    ventas.each do |v|
      precio_total = (v.precio_total).present? ? v.precio_total : 0
      ingresos_totales = ingresos_totales + precio_total
    end
    ingresos_totales
  end

  def ingresos_gastos (ingresos, gastos)
    balance_mensual = 0
    balance_mensual = ingresos - gastos
  end

  def devuelve_diferencia (anterior, actual)

    if anterior == 0
      anterior_falso = 1
      diferencia_ventas = ((actual - anterior_falso).to_f / anterior_falso) * 100
    else
      diferencia_ventas = ((actual - anterior).to_f / anterior) * 100
    end
    diferencia_ventas
  end


  #Metodo que devuelve las ventas entre los periodos
  # @params fecha_inicio [Date]
  # @params fecha_fin [Date]
  # return num_ventas[Integer], ventas_semana_hm[HashMap], ventas[ActiveRecord]
  def get_ventas_periodo(fecha_inicio, fecha_fin)
    total_semana = 0
    dia = ''
    ventas = Venta.where("created_at >= ? AND created_at < ? AND cerrada = ?", fecha_inicio, fecha_fin, true).order('created_at')

    ventas_semana_hm = {}

    Date.new(fecha_inicio.year, fecha_inicio.month, fecha_inicio.day).upto(Date.new(fecha_fin.year, fecha_fin.month, fecha_fin.day)) do |date|
      ventas_semana_hm["dia_#{date.wday}".to_sym] = {dia: date.wday, total_ventas: 0}
    end
    num_ventas = ventas.count

    ventas.each do |vsa|

      if vsa.created_at.strftime("%d/%m/%Y") != dia
        total_semana = 0
        dia = vsa.created_at.strftime("%d/%m/%Y")
        total_actual = ((vsa.precio_total).present? ? vsa.precio_total : 0)
        total_semana = total_semana + total_actual
      else
        total_actual = ((vsa.precio_total).present? ? vsa.precio_total : 0)
        total_semana = total_semana + total_actual
      end
      ventas_semana_hm["dia_#{vsa.created_at.strftime("%d/%m/%Y").to_date.wday}".to_sym] = {dia: vsa.created_at.strftime("%d/%m/%Y").to_date.wday, total_ventas: total_semana}
    end if num_ventas > 0

    return num_ventas, ventas_semana_hm, ventas

  end


  def devuelve_total_gastos(pagos)
    total_gastos = 0
    if pagos.count > 0
      pagos.each do |p|
        total_gastos = total_gastos + p.pago
      end
    else
      total_gastos = 0
    end
    return total_gastos
  end

end

app/controllers/gestion/gasolinas_controller.rb
class Gestion::GasolinasController < GestionController

  def index
    @gasolinas = Gasolina.all.order('id DESC')
  end


  def new
    fill_form
    @gasolina = Gasolina.new
  end

  def create
    gasolina = Gasolina.create(permit_params)

    if gasolina.valid?
      redirect_to gestion_gasolinas_path
    else
      @gasolina = gasolina
      render :new
    end
  end

  def edit
    fill_form
    @gasolina = Gasolina.find(params[:id])
  end

  def update
    gasolina = Gasolina.find(params[:id])
    if gasolina.update_attributes(permit_params)
      redirect_to gestion_gasolinas_path
    else
      @gasolina = gasolina
      redirect_to edit_gestion_gasolina_path(gasolina.id)
    end
  end

  def destroy
    gasolina = Gasolina.find(params[:id])
    gasolina.destroy
    redirect_to gestion_gasolinas_path
  end

  def fill_form
    @vehiculos = Vehiculo.all.order('id').map{|v| [v.nombre, v.id]}
  end

  def permit_params
    params.require(:gasolina).permit(:precio_total, :litros, :precio_litro, :vehiculo_id, :gasolinera, :tipo_gasolina, :kilometros, :fecha_repostaje)
  end
end

app/controllers/gestion/roles_controller.rb
class Gestion::RolesController < GestionController

  def index
    obtener_roles
  end

  def new
    @rol = Rol.new
  end

  def edit
    @rol = Rol.find(params[:id])
  end

  def create
    rol = Rol.create(permit_params)

    if rol.valid?
      redirect_to gestion_roles_path
    else
      @rol = rol

      render :new
    end
  end

  def update
    rol = Rol.find(params[:id])
    if rol.update_attributes(permit_params)
      redirect_to gestion_roles_path
    else
      @rol = rol
      redirect_to gestion_rol_path rol.id
    end
  end

  def destroy
    rol = Rol.find(params[:id])
    rol.destroy
    redirect_to gestion_roles_path
  end

  def permit_params
    params.require(:rol).permit(:nombre, :descripcion)
  end

  private

  def obtener_roles
    @roles = Rol.all.order('id')
  end


end

app/views/gestion/productos/_form.html.erb
<%= simple_form_for :producto, url: (@producto.new_record? ? gestion_productos_path(@producto) : gestion_producto_path(@producto)), method: (@producto.new_record? ? :post : :put), html: {class: 'form-horizontal'} do |f| %>
    <div class="ibox float-e-margins">
      <div class="ibox-content">
        <div class="row">
          <div class="col-xs-3">
            <%= f.input :nombre, placeholder: 'Nombre del producto', input_html: {class: 'form-control m-b-md'} %>
          </div>
          <div class="col-xs-3">
            <%= f.input :precio_compra, placeholder: 'Precio de compra', input_html: {class: 'form-control m-b-md'} %>
          </div>
          <div class="col-xs-3">
            <%= f.input :precio_venta, placeholder: 'Precio de venta', input_html: {class: 'form-control m-b-md'} %>
          </div>
          <div class="col-xs-3">
            <%= f.input :stock, placeholder: 'Unidades en stock', input_html: {class: 'form-control m-b-md'} %>
          </div>
          <div class="col-xs-3">
            <%= f.input :fecha_ultima_compra, as: :string, input_html: {value: fecha_legible(Date.today), class: 'datepicker form-control m-b-md'} %>
          </div>
          <div class="col-xs-3">
            <%= f.input :tipo, collection: @tipos, prompt: 'Seleccionar tipo', input_html: {class: 'form-control m-b-md'} %>
          </div>
          <div class="col-xs-3">
            <%= f.input :activo, as: :boolean, input_html: {class: 'checkbox-inline js-switch'} %>
          </div>
          <div class="col-xs-12">
            <%= f.button :submit, 'Guardar', class: 'btn btn-w-m btn-primary center-block' %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/gestion/productos/_productos.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Gestión de los productos</h5>
  </div>
  <div class="ibox-content">

    <div id="table" class="table-editable">

      <table class="table table-striped">
        <tr>
          <th>Nombre</th>
          <th>Precio compra</th>
          <th>Precio venta</th>
          <th>Stock</th>
          <th>Categoría</th>
          <th>Activo</th>
          <th>
            <%= link_to new_gestion_producto_path, :title => 'Añadir nuevo producto' do %>
              <span class="nuevo glyphicon glyphicon-plus"></span>
            <% end %></th>
        </tr>
        <% producto.each do |p| %>
          <tr id="producto_<%= p.id %>">
            <td><%= p.nombre %></td>
            <td><%= number_to_currency(p.precio_compra, :unit => '€') %></td>
            <td><%= number_to_currency(p.precio_venta, :unit => '€') %></td>
            <td><%= p.stock %>
              <% if p.stock <= session[:stock_bajo] && p.stock != 0 %>
                <span class="label label-warning">Stock bajo</span>
              <% elsif p.stock == 0 %>
                <span class="label label-danger">Sin stock</span>
              <% else %>
                <span class="label label-primary">En stock</span>
              <% end %></td>
            <td><%= p.tipo %></td>
            <td><%= boolean_to_human(p.activo).html_safe %></td>
            <td>
              <%= link_to edit_gestion_producto_path(p.id), :title => 'Editar producto' do %>
                <span class="editar fa fa-edit"></span>
              <% end %>
              <%= link_to gestion_producto_path(p.id), :confirm => "¿Estas seguro?", :method => :destroy, remote: true, :title => 'Eliminar producto' do %>
                <span class="eliminar glyphicon glyphicon-remove"></span>
              <% end %>

            </td>
          </tr>
        <% end if producto.count > 0 %>
      </table>
    </div>

  </div>
</div>

app/views/gestion/productos/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">
    <h2>Productos</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= root_path %>">Inicio</a>
      </li>
      <li>
        <a href="<%= gestion_productos_path %>">Productos</a>
      </li>
      <li class="active">
        <strong>Editando producto <%= @producto.nombre %></strong>
      </li>
    </ol>
  </div>
</div>

<div class="row wrapper wrapper-content animated fadeInRight">
  <%= render partial: 'form', locals: {producto: @producto} %>
</div>

app/views/gestion/productos/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-8">
    <h2>Servicios</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= root_path %>">Home</a>
      </li>
      <li class="active">
        <strong>Productos</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content  animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <%= render partial: 'productos', locals: {producto: @productos} %>
    </div>
  </div>
</div>

app/views/gestion/productos/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">
    <h2>Productos</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= root_path %>">Inicio</a>
      </li>
      <li>
        <a href="<%= gestion_servicios_path %>">Productos</a>
      </li>
      <li class="active">
        <strong>Nuevo Producto</strong>
      </li>
    </ol>
  </div>
</div>
<div class="row wrapper wrapper-content animated fadeInRight">
  <%= render partial: 'form', locals: {producto: @producto} %>
</div>